### ISSUE TITLE
Crash when spaces in the name

### ISSUE THREAD

**Issue by naytun** [alexiszamanidis/vscode-git-worktrees#22]
When I added a new worktree with spaces in the name, it crashed.

**Comment by alexiszamanidis** [comment]
Hi @naytun,

It seems git doesn't allow you to create a branch with spaces.

![image](https://user-images.githubusercontent.com/48658768/205705734-65d14622-d204-49d2-b6c6-3ecc8c75268b.png)

Since the name of the worktree and branch is the same, I think it would be better not to use spaces and maintain consistency.

Please let me know what you think.

I don't want to be hostile or reject you. I just express my thoughts.
 
Please let me know what you think.

**Comment by naytun** [comment]
Fist of all, I like the simplicity and easy of use of the extension. I understand the cause of this issue. But, as for a new user of this extension it would be better to mentioned that space issue somewhere in the extension (or) warn the user. My suggestion only. Thank you for the reply.

**Comment by jonz94** [comment]
Hi,
I also encounter the similar issue when I name the new branch `should-work?`.

It turns out that there are many rules about git branch name format. ([Which characters are illegal within a branch name?](https://stackoverflow.com/a/3651867/9979122))

Fortunately, we can use git's built-in [`check-ref-format`](https://git-scm.com/docs/git-check-ref-format) command to validate branch name format.

I open a PR to add this feature, hope this will make the experience better 😄
